apiVersion: v1
kind: Service
metadata:
  name: first-project
spec:
  type: NodePort
  selector:
    app: first-project
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
